export const VALID_THEMES = [
    "acceptance",
    "adaptation",
    "admiration",
    "adapting",
    "anxiety",
    "anticipation",
    "beauty",
    "best day",
    "bittersweet endings",
    "breathing",
    "celebration",
    "change",
    "cherishing",
    "childhood",
    "closure",
    "commitment",
    "comfort",
    "confession",
    "conflict",
    "consequences",
    "courage",
    "dealing with pressure",
    "deception",
    "denial",
    "desire",
    "despair",
    "devotion",
    "disillusionment",
    "distance",
    "emotional pain",
    "emotional struggle",
    "endings",
    "escape",
    "excitement",
    "family",
    "fear",
    "first love",
    "fleeting encounters",
    "forgiveness",
    "fragility",
    "freedom",
    "guilt",
    "growth",
    "haunting",
    "healing",
    "heartbreak",
    "hope",
    "identity",
    "illusions",
    "impulsivity",
    "inner conflict",
    "invisibility",
    "jealousy",
    "letting go",
    "lingering love",
    "longing",
    "loss",
    "love",
    "mementos",
    "memory",
    "moving forward",
    "moving on",
    "nostalgia",
    "panic",
    "passion",
    "perspective",
    "possessiveness",
    "realization",
    "recovery",
    "reflection",
    "reframing",
    "regret",
    "relationships",
    "relationship struggles",
    "relationship tides",
    "reminiscence",
    "resolution",
    "restlessness",
    "resilience",
    "resolve",
    "romance",
    "romantic love",
    "routine",
    "searching",
    "seasonal metaphor",
    "seizing the moment",
    "self-acceptance",
    "self-discovery",
    "self-doubt",
    "self-punishment",
    "separation",
    "secrets",
    "silence",
    "starting over",
    "summer",
    "summer romance",
    "teen romance",
    "transformation",
    "truth",
    "uncertainty",
    "unrequited love",
    "urgency",
    "validation",
    "vulnerability",
    "yearning",
    "youth",
    "youthful love"
  ];
  